/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CategoryItem: typeof import('./src/components/CategoryItem.vue')['default']
    CategoryList: typeof import('./src/components/CategoryList.vue')['default']
    FrequentPayments: typeof import('./src/components/FrequentPayments.vue')['default']
    HistoryItem: typeof import('./src/components/HistoryItem.vue')['default']
    HistoryList: typeof import('./src/components/HistoryList.vue')['default']
    Layout: typeof import('./src/components/Layout.vue')['default']
    PaymentHeader: typeof import('./src/components/PaymentHeader.vue')['default']
    PaymentHistory: typeof import('./src/components/PaymentHistory.vue')['default']
    PaymentItem: typeof import('./src/components/PaymentItem.vue')['default']
    PaymentList: typeof import('./src/components/PaymentList.vue')['default']
    PaymentPeriod: typeof import('./src/components/PaymentPeriod.vue')['default']
    PaymentsHeader: typeof import('./src/components/PaymentsHeader.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchBar: typeof import('./src/components/SearchBar.vue')['default']
    TabsBar: typeof import('./src/components/TabsBar.vue')['default']
    TheCounter: typeof import('./src/components/TheCounter.vue')['default']
    TheFooter: typeof import('./src/components/TheFooter.vue')['default']
    TheInput: typeof import('./src/components/TheInput.vue')['default']
  }
}
